# Generated by Django 3.1.1 on 2020-09-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200926_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='active',
        ),
    ]
